trigger:
- main  # Change this to your default branch name if it's not main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    git clone https://jayaf4u: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@github.com/jayaf4u/home2.git
  displayName: 'Clone GitHub repository'

- script: |
    python -m pip install --upgrade pip
    python -m pip install pycryptodome
  displayName: 'Install required packages'

- script: |
    python encrypt_data.py
  displayName: 'Execute encryption script'

- script: |
    git config --global user.name 'jayaf4u'
    git config --global user.email 'jayaf4u@gmail.com'
    cd home2
    git add encrypted_input.txt
    git commit -m "Encrypt input.txt file"
    git push origin main
  displayName: 'Commit changes and push to repository'
