trigger:
- main  # Change this to your default branch name if it's not main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    git clone https://github.com/mikeivanov/pypaillier.git
    cd pypaillier
    python setup.py install
  displayName: 'Install pypaillier'

- script: |
    git clone https://github.com/jayaf4u/home2.git
  displayName: 'Clone GitHub repository'

- script: |
    python encrypt_data.py  # Adjust this according to the name of your Python script
  displayName: 'Execute encryption script'

- script: |
    git config --global user.name 'jayaf4u'
    git config --global user.email 'jayaf4u@gmail.com'
    cd home2  # Change directory to the cloned repository
    git add encrypted_input.txt
    git commit -m "Encrypt input.txt file"
    git push origin main  # Assuming main is the target branch, adjust if necessary
  displayName: 'Commit changes and push to repository'
