trigger:
- main  # Change this to your default branch name if it's not main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    git clone https://jayaf4u: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@github.com/jayaf4u/home2.git
  displayName: 'Clone GitHub repository'

- script: |
    python -m pip install --upgrade pip
    python -m pip install pycryptodome
    pip install Pyfhel
  displayName: 'Install required packages'

- script: |
    python app.py
    mv encrypted_input.txt $(Build.ArtifactStagingDirectory)
  displayName: 'Execute encryption script and move encrypted file to artifact'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'encrypted_files'
  displayName: 'Publish encrypted files as artifact'
