trigger:
- main  # Change this to your default branch name if it's not main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    git clone https://jayaf4u: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@github.com/jayaf4u/home2.git
  displayName: 'Clone GitHub repository'

- script: |
    python -m pip install --upgrade pip
    python -m pip install pycryptodome
  displayName: 'Install required packages'

- script: |
    python encrypt_data.py
  displayName: 'Execute encryption script'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'home2/encrypted_input.txt'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/encrypted_input.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Publish artifact: encrypted_input.zip'
